In [21]:
import pandas as pd

sparcs = pd.read_csv("Data/Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2024_20260609.csv")

C:\Users\Hemanth Sai\AppData\Local\Temp\ipykernel_11464\3883517849.py:3: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  sparcs = pd.read_csv("Data/Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2024_20260609.csv")

In [22]:
print(sparcs.info())
print("Description")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(4), object(25)
memory usage: 553.1+ MB
None
Description

In [23]:
display(sparcs.describe())

,Operating Certificate Number,Permanent Facility Id,Discharge Year,APR DRG Code,APR MDC Code,APR Severity of Illness Code,Total Charges,Total Costs
count,2.191442e+06,2.191442e+06,2196737.0,2.196737e+06,2.196737e+06,2.196737e+06,2.196737e+06,2.196737e+06
mean,5.087132e+06,1.279496e+03,2024.0,4.143324e+02,1.030294e+01,2.145497e+00,9.062543e+04,2.641658e+04
std,2.245914e+06,1.869344e+03,0.0,2.440963e+02,5.985493e+00,9.252315e-01,1.894022e+05,5.537229e+04
min,1.010000e+05,1.000000e+00,2024.0,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.953000e+06,5.410000e+02,2024.0,1.940000e+02,5.000000e+00,1.000000e+00,2.357638e+04,7.415880e+03
50%,5.957001e+06,1.117000e+03,2024.0,3.830000e+02,9.000000e+00,2.000000e+00,4.724379e+04,1.411045e+04
75%,7.002032e+06,1.456000e+03,2024.0,6.400000e+02,1.500000e+01,3.000000e+00,9.451516e+04,2.778834e+04
max,7.004010e+06,1.562000e+04,2024.0,9.560000e+02,2.500000e+01,4.000000e+00,1.969486e+07,6.701232e+06

In [26]:
for col in sparcs.columns:
    print(col, ":", sparcs[col].nunique())

Health Service Area : 8
Hospital County : 57
Operating Certificate Number : 158
Permanent Facility Id : 205
Facility Name : 203
Age Group : 5
Zip Code : 50
Gender : 3
Race : 4
Ethnicity : 4
Length of Stay : 120
Type of Admission : 6
Patient Disposition : 19
Discharge Year : 1
CCSR Diagnosis Code : 478
CCSR Diagnosis Description : 478
CCSR Procedure Code : 320
CCSR Procedure Description : 320
APR DRG Code : 336
APR DRG Description : 336
APR MDC Code : 26
APR MDC Description : 26
APR Severity of Illness Code : 5
APR Severity of Illness Description : 5
APR Risk of Mortality : 5
APR Medical Surgical Description : 3
Payment Typology 1 : 9
Payment Typology 2 : 9
Payment Typology 3 : 9
Birth Weight : 121
Emergency Department Indicator : 2
Total Charges : 1926585
Total Costs : 1677228

In [30]:
nulls = pd.DataFrame({
    "Null_Count": sparcs.isnull().sum(),
    "Null_Percentage": (sparcs.isnull().sum() / len(sparcs)) * 100
})

nulls = nulls[nulls["Null_Count"] > 0]

                              Null_Count  Null_Percentage
Birth Weight                     1988915        90.539514
Payment Typology 3               1956699        89.072975
Payment Typology 2               1204408        54.827137
CCSR Procedure Code               643764        29.305465
CCSR Procedure Description        643764        29.305465
Zip Code                           41972         1.910652
Health Service Area                 5295         0.241039
Operating Certificate Number        5295         0.241039
Hospital County                     5295         0.241039
Permanent Facility Id               5295         0.241039
Payment Typology 1                   227         0.010334

In [31]:
print(nulls.sort_values("Null_Count", ascending=False))

                              Null_Count  Null_Percentage
Birth Weight                     1988915        90.539514
Payment Typology 3               1956699        89.072975
Payment Typology 2               1204408        54.827137
CCSR Procedure Code               643764        29.305465
CCSR Procedure Description        643764        29.305465
Zip Code                           41972         1.910652
Health Service Area                 5295         0.241039
Operating Certificate Number        5295         0.241039
Hospital County                     5295         0.241039
Permanent Facility Id               5295         0.241039
Payment Typology 1                   227         0.010334

In [33]:
# Top values for every categorical column

for col in sparcs.select_dtypes(include='object').columns:
    print(f"\n{col}")
    print(sparcs[col].value_counts(dropna=False).head(10))

Health Service Area
Health Service Area
New York City          996124
Long Island            359214
Hudson Valley          243870
Capital/Adirondacks    143613
Western NY             142041
Finger Lakes           140528
Central NY             138048
Southern Tier           28004
NaN                      5295
Name: count, dtype: int64

Hospital County
Hospital County
New York       389375
Kings          200536
Nassau         192048
Queens         185610
Suffolk        167166
Bronx          165312
Westchester    127036
Erie           112360
Monroe         105204
Onondaga        71592
Name: count, dtype: int64

Facility Name
Facility Name
MOUNT SINAI HOSPITAL                                             53353
NYU LANGONE HOSPITALS                                            50456
NORTH SHORE UNIVERSITY HOSPITAL                                  49153
NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRESBYTERIAN CENTER    45983
STRONG MEMORIAL HOSPITAL                                         40244
LONG ISLAND JEWISH MEDICAL CENTER                                39948
NYU LANGONE HOSPITAL-LONG ISLAND                                 38698
MONTEFIORE MEDICAL CENTER - HENRY & LUCY MOSES DIV               37784
ALBANY MEDICAL CENTER HOSPITAL                                   36882
STONY BROOK UNIVERSITY HOSPITAL                                  36013
Name: count, dtype: int64

Age Group
Age Group
70 or Older    706970
50-69          581333
30-49          423270
0-17           301927
18-29          183237
Name: count, dtype: int64

Zip Code
Zip Code
112    266231
104    207886
117    188654
100    152265
113    111758
114     87826
115     87740
OOS     65078
109     59826
105     57920
Name: count, dtype: int64

Gender
Gender
F    1195617
M    1000735
U        385
Name: count, dtype: int64

Race
Race
White                     1147354
Other Race                 620872
Black/African American     395419
Multi-racial                33092
Name: count, dtype: int64

Ethnicity
Ethnicity
Not Span/Hispanic    1540538
Spanish/Hispanic      363988
Unknown               289643
Multi-ethnic            2568
Name: count, dtype: int64

Length of Stay
Length of Stay
2     464690
1     392917
3     334224
4     214203
5     149406
6     111585
7      88766
8      67129
9      51272
10     41454
Name: count, dtype: int64

Type of Admission
Type of Admission
Emergency        1460204
Elective          355896
Newborn           198219
Urgent            168716
Trauma             10050
Not Available       3652
Name: count, dtype: int64

Patient Disposition
Patient Disposition
Home or Self Care                       1441830
Home w/ Home Health Services             299705
Skilled Nursing Home                     211258
Left Against Medical Advice               57701
Expired                                   54460
Short-term Hospital                       38487
Inpatient Rehabilitation Facility         35860
Hospice - Home                            11241
Psychiatric Hospital or Unit of Hosp       9954
Hospice - Medical Facility                 9856
Name: count, dtype: int64

CCSR Diagnosis Code
CCSR Diagnosis Code
PNL001    199274
INF002    163590
CIR019     62449
END003     43811
MBD017     39837
RSP002     37151
CIR017     37083
PRG023     37039
MBD001     36050
GEN004     33970
Name: count, dtype: int64

CCSR Diagnosis Description
CCSR Diagnosis Description
LIVEBORN                                                199274
SEPTICEMIA                                              163590
HEART FAILURE                                            62449
DIABETES MELLITUS WITH COMPLICATION                      43811
ALCOHOL-RELATED DISORDERS                                39837
PNEUMONIA (EXCEPT THAT CAUSED BY TUBERCULOSIS)           37151
CARDIAC DYSRHYTHMIAS                                     37083
COMPLICATIONS SPECIFIED DURING CHILDBIRTH                37039
SCHIZOPHRENIA SPECTRUM AND OTHER PSYCHOTIC DISORDERS     36050
URINARY TRACT INFECTIONS                                 33970
Name: count, dtype: int64

CCSR Procedure Code
CCSR Procedure Code
NaN       643764
PGN002    115706
PGN003     65817
ADM010     64265
ESA004     54012
ADM021     51708
ADM015     43394
ADM001     38452
MRS001     38159
CAR024     35384
Name: count, dtype: int64

CCSR Procedure Description
CCSR Procedure Description
NaN                                              643764
SPONTANEOUS VAGINAL DELIVERY                     115706
CESAREAN SECTION                                  65817
VACCINATIONS                                      64265
NON-INVASIVE VENTILATION                          54012
ADMINISTRATION OF THERAPEUTIC SUBSTANCES, NEC     51708
ADMINISTRATION OF ANTIBIOTICS                     43394
TRANSFUSION OF BLOOD AND BLOOD PRODUCTS           38452
CIRCUMCISION                                      38159
VENOUS AND ARTERIAL CATHETER PLACEMENT            35384
Name: count, dtype: int64

APR DRG Description
APR DRG Description
NEONATE BIRTH WEIGHT > 2499 GRAMS, NORMAL NEWBORN OR NEONATE WITH OTHER PROBLEM    168494
SEPTICEMIA AND DISSEMINATED INFECTIONS                                             144367
VAGINAL DELIVERY                                                                   123398
HEART FAILURE                                                                       60015
CESAREAN SECTION WITHOUT STERILIZATION                                              59419
OTHER PNEUMONIA                                                                     33096
KIDNEY AND URINARY TRACT INFECTIONS                                                 32638
MAJOR RESPIRATORY INFECTIONS AND INFLAMMATIONS                                      30700
SCHIZOPHRENIA                                                                       29639
CVA AND PRECEREBRAL OCCLUSION WITH INFARCTION                                       27317
Name: count, dtype: int64

APR MDC Description
APR MDC Description
DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM                        277625
PREGNANCY, CHILDBIRTH AND THE PUERPERIUM                                219991
NEWBORNS AND OTHER NEONATES WITH CONDTN ORIG IN PERINATAL PERIOD        203604
INFECTIOUS AND PARASITIC DISEASES, SYSTEMIC OR UNSPECIFIED SITES        183022
DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM                        180502
DISEASES AND DISORDERS OF THE DIGESTIVE SYSTEM                          172157
DISEASES AND DISORDERS OF THE MUSCULOSKELETAL SYSTEM AND CONN TISSUE    171033
DISEASES AND DISORDERS OF THE NERVOUS SYSTEM                            162025
DISEASES AND DISORDERS OF THE KIDNEY AND URINARY TRACT                  107160
MENTAL DISEASES AND DISORDERS                                            87648
Name: count, dtype: int64

APR Severity of Illness Description
APR Severity of Illness Description
Moderate        820465
Minor           619207
Major           573480
Extreme         183129
Undetermined       456
Name: count, dtype: int64

APR Risk of Mortality
APR Risk of Mortality
Minor           1108093
Moderate         477108
Major            440239
Extreme          170841
Undetermined        456
Name: count, dtype: int64

APR Medical Surgical Description
APR Medical Surgical Description
Medical           1686244
Surgical           510037
Not Applicable        456
Name: count, dtype: int64

Payment Typology 1
Payment Typology 1
Medicare                     929267
Medicaid                     635606
Private Health Insurance     317827
Blue Cross/Blue Shield       204165
Self-Pay                      34786
Managed Care, Unspecified     30320
Miscellaneous/Other           21764
Federal/State/Local/VA        21140
Department of Corrections      1635
NaN                             227
Name: count, dtype: int64

Payment Typology 2
Payment Typology 2
NaN                          1204408
Medicaid                      420954
Medicare                      168543
Private Health Insurance      153534
Self-Pay                      121540
Blue Cross/Blue Shield        105859
Federal/State/Local/VA         13178
Managed Care, Unspecified       5527
Miscellaneous/Other             3081
Department of Corrections        113
Name: count, dtype: int64

Payment Typology 3
Payment Typology 3
NaN                          1956699
Self-Pay                      124253
Medicaid                       67477
Private Health Insurance       19825
Blue Cross/Blue Shield         13845
Medicare                       11800
Federal/State/Local/VA          2061
Managed Care, Unspecified        470
Miscellaneous/Other              288
Department of Corrections         19
Name: count, dtype: int64

Birth Weight
Birth Weight
NaN       1988915
3200         9156
3300         9076
3100         8817
3400         8768
3200.0       8271
3000         7966
3300.0       7959
3500         7684
3400.0       7596
Name: count, dtype: int64

Emergency Department Indicator
Emergency Department Indicator
Y    1377141
N     819596
Name: count, dtype: int64

In [34]:
# Numerical columns

sparcs[['Total Charges','Total Costs']].describe()

# Top expensive records

sparcs.nlargest(
    10,
    'Total Charges'
)[[
    'Facility Name',
    'CCSR Diagnosis Description',
    'Total Charges',
    'Total Costs',
    'Length of Stay'
]]

,Facility Name,CCSR Diagnosis Description,Total Charges,Total Costs,Length of Stay
1957931,MOUNT SINAI HOSPITAL,OTHER SPECIFIED AND UNSPECIFIED LIVER DISEASE,19694856.95,5118572.80,120+
1404028,MONTEFIORE MEDICAL CENTER - HENRY & LUCY MOSES...,HEPATIC FAILURE,17986728.46,2929418.55,120+
1843236,NYU LANGONE HOSPITALS,SKIN AND SUBCUTANEOUS TISSUE INFECTIONS,17981038.51,1479772.46,6
1466130,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,CARDIAC AND CIRCULATORY CONGENITAL ANOMALIES,17102848.93,6001046.06,120+
1492379,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,MYOCARDITIS AND CARDIOMYOPATHY,16668416.71,5760409.18,120+
73094,DAVID H. KOCH CENTER FOR CANCER CARE,DISEASES OF WHITE BLOOD CELLS,16505368.62,4742944.26,110
1000945,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,RHEUMATOID ARTHRITIS AND RELATED DISEASE,16208639.65,4948973.60,120+
71632,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,COMA; STUPOR; AND BRAIN DAMAGE,15557537.27,3751355.50,120+
1086735,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,PULMONARY HEART DISEASE,14793875.89,4299613.82,120+
1393866,NYU LANGONE HOSPITALS,COMPLICATION OF OTHER SURGICAL OR MEDICAL CARE...,14494399.00,5393586.77,120+

In [35]:
sparcs.nlargest(
    10,
    'Total Costs'
)[[
    'Facility Name',
    'CCSR Diagnosis Description',
    'Total Charges',
    'Total Costs',
    'Length of Stay'
]]

,Facility Name,CCSR Diagnosis Description,Total Charges,Total Costs,Length of Stay
699596,BELLEVUE HOSPITAL CENTER,"TRAUMATIC BRAIN INJURY (TBI); CONCUSSION, INIT...",14356481.35,6701232.23,120+
1466130,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,CARDIAC AND CIRCULATORY CONGENITAL ANOMALIES,17102848.93,6001046.06,120+
1381322,BELLEVUE HOSPITAL CENTER,OTHER NERVOUS SYSTEM DISORDERS (OFTEN HEREDITA...,12599457.48,5881099.17,120+
1377812,NORTH SHORE UNIVERSITY HOSPITAL,SEPTICEMIA,100597.03,5877198.55,3
1492379,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,MYOCARDITIS AND CARDIOMYOPATHY,16668416.71,5760409.18,120+
1393866,NYU LANGONE HOSPITALS,COMPLICATION OF OTHER SURGICAL OR MEDICAL CARE...,14494399.00,5393586.77,120+
1957931,MOUNT SINAI HOSPITAL,OTHER SPECIFIED AND UNSPECIFIED LIVER DISEASE,19694856.95,5118572.80,120+
1000945,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,RHEUMATOID ARTHRITIS AND RELATED DISEASE,16208639.65,4948973.60,120+
73094,DAVID H. KOCH CENTER FOR CANCER CARE,DISEASES OF WHITE BLOOD CELLS,16505368.62,4742944.26,110
1666049,NEW YORK-PRESBYTERIAN HOSPITAL - NEW YORK WEIL...,SEPTICEMIA,13994173.42,4394668.03,120+