## **Data Profiling**

In [47]:
import pandas as pd
import numpy as np

#### Load Datasets

In [48]:
years = [2011, 2012, 2014, 2018, 2021, 2023, 2024]

datasets = {}

for year in years:
    datasets[year] = pd.read_csv(
        f"../data/sparcs_{year}_raw.csv",
        low_memory=False
    )

#### Summary

In [49]:
summary = []

for year, df in datasets.items():
    summary.append({
        "Year": year,
        "Rows": len(df),
        "Columns": df.shape[1],
        "Memory (MB)": round(df.memory_usage(deep=True).sum() / 1024**2, 2)
    })

summary_df = pd.DataFrame(summary)

display(summary_df)

   Year     Rows  Columns  Memory (MB)
0  2011  2589121       33      3956.70
1  2012  2544543       33      3925.74
2  2014  2367550       33      3648.82
3  2018  2352807       33      3764.00
4  2021  2135260       33      3533.54
5  2023  2125754       33      3738.65
6  2024  2196737       33      3620.24

#### Schema Comparison & Validation

In [50]:
reference_columns = datasets[2024].columns

for year, df in datasets.items():

    print(f"\n{'='*60}")
    print(f"{year}")
    print("="*60)

    if reference_columns.equals(df.columns):
        print("✅ Column names and order match 2024")
    else:
        print("❌ Schema mismatch")

============================================================
2011
============================================================
✅ Column names and order match 2024

============================================================
2012
============================================================
✅ Column names and order match 2024

============================================================
2014
============================================================
✅ Column names and order match 2024

============================================================
2018
============================================================
✅ Column names and order match 2024

============================================================
2021
============================================================
✅ Column names and order match 2024

============================================================
2023
============================================================
✅ Column names and order match 2024

============================================================
2024
============================================================
✅ Column names and order match 2024

In [51]:
reference = datasets[2024].columns.tolist()

for year, df in datasets.items():

    if year == 2024:
        continue

    cols = df.columns.tolist()

    print(f"\n{'='*70}")
    print(f"{year}")
    print("="*70)

    extra = sorted(set(cols) - set(reference))
    missing = sorted(set(reference) - set(cols))

    print("Extra Columns:")
    print(extra if extra else "None")

    print("\nMissing Columns:")
    print(missing if missing else "None")

======================================================================
2011
======================================================================
Extra Columns:
None

Missing Columns:
None

======================================================================
2012
======================================================================
Extra Columns:
None

Missing Columns:
None

======================================================================
2014
======================================================================
Extra Columns:
None

Missing Columns:
None

======================================================================
2018
======================================================================
Extra Columns:
None

Missing Columns:
None

======================================================================
2021
======================================================================
Extra Columns:
None

Missing Columns:
None

======================================================================
2023
======================================================================
Extra Columns:
None

Missing Columns:
None

In [52]:
# -----------------------------
# Standardize All Datasets
# -----------------------------

rename_map = {
    "Facility ID": "Permanent Facility Id",
    "Hospital Service Area": "Health Service Area",
    "Zip Code - 3 digits": "Zip Code",

    "CCS Diagnosis Code": "CCSR Diagnosis Code",
    "CCS Diagnosis Description": "CCSR Diagnosis Description",

    "CCS Procedure Code": "CCSR Procedure Code",
    "CCS Procedure Description": "CCSR Procedure Description",

    "Source of Payment 1": "Payment Typology 1",
    "Source of Payment 2": "Payment Typology 2",
    "Source of Payment 3": "Payment Typology 3"
}

for year, df in datasets.items():

    # Rename columns
    df.rename(columns=rename_map, inplace=True)

    # Drop legacy column if present
    df.drop(columns=["Abortion Edit Indicator"], errors="ignore", inplace=True)
    df.to_csv(f"../data/sparcs_{year}_raw.csv", index=False)

In [53]:
reference_columns = datasets[2024].columns

for year, df in datasets.items():

    print(f"\n{'='*60}")
    print(year)
    print("="*60)

    if reference_columns.equals(df.columns):
        print("✅ Column names and order match 2024")
    else:
        print("❌ Schema mismatch")

============================================================
2011
============================================================
✅ Column names and order match 2024

============================================================
2012
============================================================
✅ Column names and order match 2024

============================================================
2014
============================================================
✅ Column names and order match 2024

============================================================
2018
============================================================
✅ Column names and order match 2024

============================================================
2021
============================================================
✅ Column names and order match 2024

============================================================
2023
============================================================
✅ Column names and order match 2024

============================================================
2024
============================================================
✅ Column names and order match 2024

### Data INFO

In [54]:
for year, df in datasets.items():

    print(f"\n{'='*80}")
    print(f"{year}")
    print("="*80)

    df.info()

================================================================================
2011
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589121 entries, 0 to 2589120
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  int64
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  int64
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         int64
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(7), object(22)
memory usage: 651.9+ MB

================================================================================
2012
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544543 entries, 0 to 2544542
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  int64
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  int64
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         int64
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(7), object(22)
memory usage: 640.6+ MB

================================================================================
2014
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2367550 entries, 0 to 2367549
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  int64
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  int64
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         int64
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(7), object(22)
memory usage: 596.1+ MB

================================================================================
2018
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2352807 entries, 0 to 2352806
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         float64
 19  APR DRG Description                  object
 20  APR MDC Code                         float64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         float64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       bool
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: bool(1), float64(7), int64(1), object(24)
memory usage: 576.7+ MB

================================================================================
2021
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2135260 entries, 0 to 2135259
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(4), object(25)
memory usage: 537.6+ MB

================================================================================
2023
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2125754 entries, 0 to 2125753
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 535.2+ MB

================================================================================
2024
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(4), object(25)
memory usage: 553.1+ MB

### Missing Values

In [55]:
for year, df in datasets.items():

    print(f"\n{'='*80}")
    print(f"Missing Values - {year}")
    print("="*80)

    nulls = pd.DataFrame({
        "Null Count": df.isnull().sum(),
        "Null %": (df.isnull().mean()*100).round(2)
    })

    display(nulls[nulls["Null Count"]>0].sort_values("Null Count", ascending=False))

================================================================================
Missing Values - 2011
================================================================================

                                     Null Count  Null %
Payment Typology 3                      1854118   71.61
Payment Typology 2                       773485   29.87
Zip Code                                   6348    0.25
Health Service Area                        4606    0.18
Hospital County                            4606    0.18
Permanent Facility Id                      4606    0.18
Operating Certificate Number               4606    0.18
APR Risk of Mortality                        77    0.00
APR Severity of Illness Description          77    0.00

================================================================================
Missing Values - 2012
================================================================================

                                     Null Count  Null %
Payment Typology 3                      1824441   71.70
Payment Typology 2                       763177   29.99
Zip Code                                  38670    1.52
Health Service Area                        6788    0.27
Hospital County                            6788    0.27
Permanent Facility Id                      6788    0.27
Operating Certificate Number               6788    0.27
APR Risk of Mortality                        89    0.00
APR Severity of Illness Description          89    0.00

================================================================================
Missing Values - 2014
================================================================================

                                     Null Count  Null %
Payment Typology 3                      1682232   71.05
Payment Typology 2                       785445   33.18
Zip Code                                  37188    1.57
Health Service Area                        6047    0.26
Hospital County                            6047    0.26
Permanent Facility Id                      6047    0.26
Operating Certificate Number               6047    0.26
APR Risk of Mortality                        49    0.00
APR Severity of Illness Description          49    0.00

================================================================================
Missing Values - 2018
================================================================================

                                     Null Count  Null %
Birth Weight                            2129935   90.53
Payment Typology 3                      1852299   78.73
Payment Typology 2                       917662   39.00
CCSR Procedure Code                      717350   30.49
CCSR Procedure Description               717350   30.49
Zip Code                                  42091    1.79
Health Service Area                        8948    0.38
Operating Certificate Number               8948    0.38
Hospital County                            8948    0.38
Permanent Facility Id                      8804    0.37
APR Severity of Illness Description         158    0.01
APR Risk of Mortality                       158    0.01
CCSR Diagnosis Description                   59    0.00
CCSR Diagnosis Code                          59    0.00
APR DRG Code                                  3    0.00
APR DRG Description                           3    0.00
APR Severity of Illness Code                  3    0.00
APR MDC Code                                  3    0.00
APR MDC Description                           3    0.00

================================================================================
Missing Values - 2021
================================================================================

                                     Null Count  Null %
Birth Weight                            1925333   90.17
Payment Typology 3                      1803108   84.44
Payment Typology 2                      1097001   51.38
CCSR Procedure Code                      583187   27.31
CCSR Procedure Description               583187   27.31
Zip Code                                  40246    1.88
Operating Certificate Number               6663    0.31
Health Service Area                        5214    0.24
Permanent Facility Id                      5214    0.24
Hospital County                            5214    0.24
APR Severity of Illness Description         589    0.03
APR Risk of Mortality                       589    0.03

================================================================================
Missing Values - 2023
================================================================================

                                     Null Count  Null %
Birth Weight                            1921751   90.40
Payment Typology 3                      1843136   86.71
Payment Typology 2                      1114046   52.41
CCSR Procedure Code                      611024   28.74
CCSR Procedure Description               611024   28.74
Zip Code                                  41883    1.97
Hospital County                            5333    0.25
Health Service Area                        5333    0.25
Permanent Facility Id                      5333    0.25
Operating Certificate Number               5333    0.25
APR Severity of Illness Description         474    0.02
APR Risk of Mortality                       474    0.02

================================================================================
Missing Values - 2024
================================================================================

                              Null Count  Null %
Birth Weight                     1988915   90.54
Payment Typology 3               1956699   89.07
Payment Typology 2               1204408   54.83
CCSR Procedure Code               643764   29.31
CCSR Procedure Description        643764   29.31
Zip Code                           41972    1.91
Health Service Area                 5295    0.24
Operating Certificate Number        5295    0.24
Hospital County                     5295    0.24
Permanent Facility Id               5295    0.24
Payment Typology 1                   227    0.01

#### Unique Values

In [56]:
for year, df in datasets.items():

    print(f"\n{'='*80}")
    print(f"Unique Values - {year}")
    print("="*80)

    display(pd.DataFrame({
        "Column": df.columns,
        "Unique Values": df.nunique()
    }))

================================================================================
Unique Values - 2011
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,189
Permanent Facility Id,Permanent Facility Id,224
Facility Name,Facility Name,225
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,3
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,19
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,263
CCSR Diagnosis Description,CCSR Diagnosis Description,263
CCSR Procedure Code,CCSR Procedure Code,233
CCSR Procedure Description,CCSR Procedure Description,233
APR DRG Code,APR DRG Code,316
APR DRG Description,APR DRG Description,316
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,4
APR Risk of Mortality,APR Risk of Mortality,4
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,10
Payment Typology 2,Payment Typology 2,10
Payment Typology 3,Payment Typology 3,10
Birth Weight,Birth Weight,91
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1807518
Total Costs,Total Costs,1462845

================================================================================
Unique Values - 2012
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,188
Permanent Facility Id,Permanent Facility Id,223
Facility Name,Facility Name,239
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,3
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,19
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,262
CCSR Diagnosis Description,CCSR Diagnosis Description,262
CCSR Procedure Code,CCSR Procedure Code,231
CCSR Procedure Description,CCSR Procedure Description,231
APR DRG Code,APR DRG Code,316
APR DRG Description,APR DRG Description,316
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,4
APR Risk of Mortality,APR Risk of Mortality,4
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,10
Payment Typology 2,Payment Typology 2,10
Payment Typology 3,Payment Typology 3,10
Birth Weight,Birth Weight,80
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1819939
Total Costs,Total Costs,1450936

================================================================================
Unique Values - 2014
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,182
Permanent Facility Id,Permanent Facility Id,215
Facility Name,Facility Name,231
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,4
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,19
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,262
CCSR Diagnosis Description,CCSR Diagnosis Description,262
CCSR Procedure Code,CCSR Procedure Code,233
CCSR Procedure Description,CCSR Procedure Description,233
APR DRG Code,APR DRG Code,316
APR DRG Description,APR DRG Description,316
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,4
APR Risk of Mortality,APR Risk of Mortality,4
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,10
Payment Typology 2,Payment Typology 2,10
Payment Typology 3,Payment Typology 3,10
Birth Weight,Birth Weight,74
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1771647
Total Costs,Total Costs,1463831

================================================================================
Unique Values - 2018
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,170
Permanent Facility Id,Permanent Facility Id,209
Facility Name,Facility Name,206
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,4
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,20
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,480
CCSR Diagnosis Description,CCSR Diagnosis Description,480
CCSR Procedure Code,CCSR Procedure Code,317
CCSR Procedure Description,CCSR Procedure Description,317
APR DRG Code,APR DRG Code,328
APR DRG Description,APR DRG Description,328
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,4
APR Risk of Mortality,APR Risk of Mortality,4
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,9
Payment Typology 2,Payment Typology 2,9
Payment Typology 3,Payment Typology 3,9
Birth Weight,Birth Weight,75
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1895396
Total Costs,Total Costs,1552686

================================================================================
Unique Values - 2021
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,168
Permanent Facility Id,Permanent Facility Id,204
Facility Name,Facility Name,204
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,4
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,19
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,478
CCSR Diagnosis Description,CCSR Diagnosis Description,478
CCSR Procedure Code,CCSR Procedure Code,321
CCSR Procedure Description,CCSR Procedure Description,321
APR DRG Code,APR DRG Code,334
APR DRG Description,APR DRG Description,334
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,4
APR Risk of Mortality,APR Risk of Mortality,4
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,9
Payment Typology 2,Payment Typology 2,9
Payment Typology 3,Payment Typology 3,9
Birth Weight,Birth Weight,71
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1846189
Total Costs,Total Costs,1568863

================================================================================
Unique Values - 2023
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,160
Permanent Facility Id,Permanent Facility Id,207
Facility Name,Facility Name,206
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,4
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,19
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,482
CCSR Diagnosis Description,CCSR Diagnosis Description,482
CCSR Procedure Code,CCSR Procedure Code,320
CCSR Procedure Description,CCSR Procedure Description,320
APR DRG Code,APR DRG Code,335
APR DRG Description,APR DRG Description,335
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,4
APR Risk of Mortality,APR Risk of Mortality,4
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,9
Payment Typology 2,Payment Typology 2,9
Payment Typology 3,Payment Typology 3,9
Birth Weight,Birth Weight,81
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1864848
Total Costs,Total Costs,1616535

================================================================================
Unique Values - 2024
================================================================================

,Column,Unique Values
Health Service Area,Health Service Area,8
Hospital County,Hospital County,57
Operating Certificate Number,Operating Certificate Number,158
Permanent Facility Id,Permanent Facility Id,205
Facility Name,Facility Name,203
Age Group,Age Group,5
Zip Code,Zip Code,50
Gender,Gender,3
Race,Race,4
Ethnicity,Ethnicity,4
Length of Stay,Length of Stay,120
Type of Admission,Type of Admission,6
Patient Disposition,Patient Disposition,19
Discharge Year,Discharge Year,1
CCSR Diagnosis Code,CCSR Diagnosis Code,478
CCSR Diagnosis Description,CCSR Diagnosis Description,478
CCSR Procedure Code,CCSR Procedure Code,320
CCSR Procedure Description,CCSR Procedure Description,320
APR DRG Code,APR DRG Code,336
APR DRG Description,APR DRG Description,336
APR MDC Code,APR MDC Code,26
APR MDC Description,APR MDC Description,26
APR Severity of Illness Code,APR Severity of Illness Code,5
APR Severity of Illness Description,APR Severity of Illness Description,5
APR Risk of Mortality,APR Risk of Mortality,5
APR Medical Surgical Description,APR Medical Surgical Description,3
Payment Typology 1,Payment Typology 1,9
Payment Typology 2,Payment Typology 2,9
Payment Typology 3,Payment Typology 3,9
Birth Weight,Birth Weight,67
Emergency Department Indicator,Emergency Department Indicator,2
Total Charges,Total Charges,1926585
Total Costs,Total Costs,1677228

#### Description

In [57]:
for year, df in datasets.items():

    print(f"\n{'='*80}")
    print(f"Describe - {year}")
    print("="*80)

    display(df.describe(include='all').T)

================================================================================
Describe - 2011
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2584515,8,New York City,1206833,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2584515,57,Manhattan,429648,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2584515.0,NaN,NaN,NaN,5006666.194054,2249886.224561,101000.0,2951001.0,5907001.0,7002002.0,7004010.0
Permanent Facility Id,2584515.0,NaN,NaN,NaN,1034.659647,654.217195,1.0,541.0,1099.0,1450.0,9250.0
Facility Name,2589121,225,Mount Sinai Hospital,57286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2589121,5,70 or Older,716158,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2582773,50,112,355821,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2589121,3,F,1458160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2589121,4,White,1555193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2589121,3,Not Span/Hispanic,2148436,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2589121,120,2,578225,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2589121,6,Emergency,1628763,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2589121,19,Home or Self Care,1759889,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2589121.0,NaN,NaN,NaN,2011.0,0.0,2011.0,2011.0,2011.0,2011.0,2011.0
CCSR Diagnosis Code,2589121.0,NaN,NaN,NaN,191.753401,157.146037,1.0,106.0,157.0,218.0,999.0
CCSR Diagnosis Description,2589121,263,LIVEBORN,237514,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,2589121.0,NaN,NaN,NaN,113.48127,87.796411,0.0,0.0,132.0,213.0,999.0
CCSR Procedure Description,2589121,233,NO PROC,650329,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2589121.0,NaN,NaN,NaN,408.508601,240.678904,1.0,198.0,363.0,640.0,956.0
APR DRG Description,2589121,316,"NEONATE BIRTHWT >2499G, NORMAL NEWBORN OR NEON...",207171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2589121.0,NaN,NaN,NaN,10.206173,5.935382,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2589121,26,Diseases and Disorders of the Circulatory System,371745,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2589121.0,NaN,NaN,NaN,1.978787,0.906401,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2589044,4,Moderate,952414,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2589044,4,Minor,1597985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2589121,3,Medical,1985315,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2589121,10,Medicare,957126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,1815636,10,Medicaid,589660,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,735003,10,Self-Pay,491926,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,2589121.0,NaN,NaN,NaN,309.531806,976.742234,0.0,0.0,0.0,0.0,9900.0
Emergency Department Indicator,2589121,2,Y,1505997,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2589121.0,NaN,NaN,NaN,31319.839723,59574.135675,0.01,8420.71,16761.0,33653.98,6189492.22
Total Costs,2589121.0,NaN,NaN,NaN,12015.723065,25048.198903,0.0,3491.27,6497.18,12713.28,4017779.91

================================================================================
Describe - 2012
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2537755,8,New York City,1197768,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2537755,57,Manhattan,432513,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2537755.0,NaN,NaN,NaN,5021651.198469,2250693.361946,101000.0,2951001.0,5907001.0,7002002.0,7004010.0
Permanent Facility Id,2537755.0,NaN,NaN,NaN,1043.646685,691.659353,1.0,541.0,1122.0,1450.0,9250.0
Facility Name,2544543,239,Mount Sinai Hospital,58722,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2544543,5,70 or Older,697658,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2505873,50,112,352179,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2544543,3,F,1431359,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2544543,4,White,1450676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2544543,3,Not Span/Hispanic,2099400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2544543,120,2,575841,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2544543,6,Emergency,1601437,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2544543,19,Home or Self Care,1723214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2544543.0,NaN,NaN,NaN,2012.0,0.0,2012.0,2012.0,2012.0,2012.0,2012.0
CCSR Diagnosis Code,2544543.0,NaN,NaN,NaN,191.909003,157.580872,1.0,106.0,159.0,218.0,670.0
CCSR Diagnosis Description,2544543,262,Liveborn,237371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,2544543.0,NaN,NaN,NaN,114.517241,87.774821,0.0,1.0,134.0,213.0,231.0
CCSR Procedure Description,2544543,231,NO PROC,630752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2544543.0,NaN,NaN,NaN,410.772558,240.726215,1.0,198.0,382.0,640.0,956.0
APR DRG Description,2544543,316,"Neonate birthwt >2499g, normal newborn or neon...",207764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2544543.0,NaN,NaN,NaN,10.261423,5.937516,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2544543,26,Diseases and Disorders of the Circulatory System,351437,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2544543.0,NaN,NaN,NaN,1.998949,0.912266,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2544454,4,Moderate,935541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2544454,4,Minor,1554731,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2544543,3,Medical,1953711,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2544543,10,Medicare,954141,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,1781366,10,Medicaid,605007,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,720102,10,Self-Pay,515749,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,2544543.0,NaN,NaN,NaN,310.654133,967.398939,0.0,0.0,0.0,0.0,9000.0
Emergency Department Indicator,2544543,2,Y,1493424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2544543.0,NaN,NaN,NaN,33346.467601,62908.467987,0.31,8937.035,17852.95,35916.625,7066435.82
Total Costs,2544543.0,NaN,NaN,NaN,12102.245369,32664.909585,0.1,3598.74,6659.15,12820.26,32311386.12

================================================================================
Describe - 2014
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2361503,8,New York City,1112216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2361503,57,Manhattan,410835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2361503.0,NaN,NaN,NaN,5024810.248698,2254119.613992,101000.0,2951001.0,5907002.0,7002009.0,7004010.0
Permanent Facility Id,2361503.0,NaN,NaN,NaN,1047.810057,717.040418,1.0,541.0,1117.0,1450.0,9431.0
Facility Name,2367550,231,Mount Sinai Hospital,56020,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2367550,5,50 to 69,644620,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2330362,50,112,322185,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2367550,3,F,1325379,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2367550,4,White,1344542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2367550,4,Not Span/Hispanic,1944197,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2367550,120,2,547187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2367550,6,Emergency,1495700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2367550,19,Home or Self Care,1583211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2367550.0,NaN,NaN,NaN,2014.0,0.0,2014.0,2014.0,2014.0,2014.0,2014.0
CCSR Diagnosis Code,2367550.0,NaN,NaN,NaN,191.566728,158.899785,1.0,106.0,159.0,218.0,670.0
CCSR Diagnosis Description,2367550,262,Liveborn,232250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,2367550.0,NaN,NaN,NaN,116.165223,87.532732,0.0,4.0,134.0,216.0,999.0
CCSR Procedure Description,2367550,233,NO PROC,566631,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2367550.0,NaN,NaN,NaN,417.587678,240.586497,1.0,201.0,383.0,640.0,956.0
APR DRG Description,2367550,316,"Neonate birthwt >2499g, normal newborn or neon...",203593,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2367550.0,NaN,NaN,NaN,10.429571,5.921187,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2367550,26,Diseases and Disorders of the Circulatory System,297810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2367550.0,NaN,NaN,NaN,1.973466,0.88761,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2367501,4,Moderate,908166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2367501,4,Minor,1436544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2367550,3,Medical,1804669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2367550,10,Medicare,879240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,1582105,10,Medicaid,546903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,685318,10,Self-Pay,478108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,2367550.0,NaN,NaN,NaN,326.9781,990.705503,0.0,0.0,0.0,0.0,8400.0
Emergency Department Indicator,2367550,2,Y,1370728,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2367550.0,NaN,NaN,NaN,40187.879426,73971.054324,0.5,11153.185,21860.05,43245.1825,8593455.88
Total Costs,2367550.0,NaN,NaN,NaN,13638.455331,25645.957581,0.14,4084.8525,7573.875,14680.9575,3960368.93

================================================================================
Describe - 2018
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2343859,8,New York City,1064402,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2343859,57,Manhattan,391214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2343859.0,NaN,NaN,NaN,4962919.648501,2273135.777031,101000.0,2951001.0,5903001.0,7002017.0,7004010.0
Permanent Facility Id,2344003.0,NaN,NaN,NaN,1035.171937,725.803178,1.0,528.0,1072.0,1453.0,10216.0
Facility Name,2352807,206,Mount Sinai Hospital,52702,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2352807,5,70 or Older,684293,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2310716,50,112,294169,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2352807,3,F,1295305,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2352807,4,White,1318295,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2352807,4,Not Span/Hispanic,1876451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2352807,120,2,544865,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2352807,6,Emergency,1525053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2352807,20,Home or Self Care,1545370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2352807.0,NaN,NaN,NaN,2018.0,0.0,2018.0,2018.0,2018.0,2018.0,2018.0
CCSR Diagnosis Code,2352748,480,PNL001,214978,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Diagnosis Description,2352748,480,LIVEBORN,214978,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,1635457,317,PGN002,122107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Description,1635457,317,SPONTANEOUS VAGINAL DELIVERY,122107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2352804.0,NaN,NaN,NaN,415.367056,242.289494,1.0,197.0,383.0,640.0,956.0
APR DRG Description,2352804,328,"NEONATE BIRTHWT >2499G, NORMAL NEWBORN OR NEON...",188596,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2352804.0,NaN,NaN,NaN,10.341191,5.93613,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2352804,26,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM,299290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2352804.0,NaN,NaN,NaN,2.086185,0.919281,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2352649,4,Moderate,890604,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2352649,4,Minor,1299998,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2352807,3,Medical,1787229,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2352807,9,Medicare,932344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,1435145,9,Medicaid,544211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,500508,9,Self-Pay,314034,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,222872,75,03200,18381,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Emergency Department Indicator,2352807,2,True,1381321,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2352807.0,NaN,NaN,NaN,53864.090971,104066.58842,0.0,14440.4,28623.52,57383.955,8176580.28
Total Costs,2352807.0,NaN,NaN,NaN,16531.089997,33438.826709,0.0,4888.725,9144.18,17504.3,3264236.68

================================================================================
Describe - 2021
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2130046,8,New York City,948517,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2130046,57,Manhattan,366442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2128597.0,NaN,NaN,NaN,4957985.457382,2261388.297997,101000.0,2951001.0,5902001.0,7002020.0,7004010.0
Permanent Facility Id,2130046.0,NaN,NaN,NaN,1027.173082,715.216373,1.0,528.0,1045.0,1453.0,10355.0
Facility Name,2135260,204,Mount Sinai Hospital,49972,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2135260,5,70 or Older,630265,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2095014,50,112,260307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2135260,3,F,1163725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2135260,4,White,1161894,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2135260,4,Not Span/Hispanic,1600636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2135260,120,2,471206,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2135260,6,Emergency,1405370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2135260,19,Home or Self Care,1397511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2135260.0,NaN,NaN,NaN,2021.0,0.0,2021.0,2021.0,2021.0,2021.0,2021.0
CCSR Diagnosis Code,2135260,478,PNL001,202001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Diagnosis Description,2135260,478,Liveborn,202001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,1552073,321,PGN002,115171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Description,1552073,321,SPONTANEOUS VAGINAL DELIVERY,115171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2135260.0,NaN,NaN,NaN,414.051493,244.066951,1.0,194.0,383.0,640.0,956.0
APR DRG Description,2135260,334,"NEONATE BIRTH WEIGHT > 2499 GRAMS, NORMAL NEWB...",174868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2135260.0,NaN,NaN,NaN,10.307199,5.965352,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2135260,26,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM,263947,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2135260.0,NaN,NaN,NaN,2.141359,0.975567,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2134671,4,Moderate,772195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2134671,4,Minor,1085541,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2135260,3,Medical,1634307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2135260,9,Medicare,841481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,1038259,9,Medicaid,421231,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,332152,9,Self-Pay,204561,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,209927,71,03200,17354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Emergency Department Indicator,2135260,2,Y,1335897,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2135260.0,NaN,NaN,NaN,72834.984211,148598.437531,0.34,18952.3725,38122.195,76688.205,17935752.0
Total Costs,2135260.0,NaN,NaN,NaN,21895.112515,46993.706311,0.15,5995.5575,11530.71,22956.025,12392868.33

================================================================================
Describe - 2023
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2120421,8,New York City,963525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2120421,57,Manhattan,377402,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2120421.0,NaN,NaN,NaN,5086379.338246,2240880.801965,101000.0,2953000.0,5957001.0,7002032.0,7004010.0
Permanent Facility Id,2120421.0,NaN,NaN,NaN,1127.537116,1181.425245,1.0,541.0,1097.0,1454.0,15485.0
Facility Name,2125754,206,North Shore University Hospital,49154,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2125754,5,70 or Older,665216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2083871,50,112,255597,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2125754,3,F,1158896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2125754,4,White,1117779,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2125754,4,Not Span/Hispanic,1501423,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2125754,120,2,456193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2125754,6,Emergency,1410175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2125754,19,Home or Self Care,1405879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2125754.0,NaN,NaN,NaN,2023.0,0.0,2023.0,2023.0,2023.0,2023.0,2023.0
CCSR Diagnosis Code,2125754,482,PNL001,195421,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Diagnosis Description,2125754,482,Liveborn,195421,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,1514730,320,PGN002,114301,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Description,1514730,320,SPONTANEOUS VAGINAL DELIVERY,114301,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2125754.0,NaN,NaN,NaN,413.389768,243.15823,1.0,194.0,383.0,640.0,956.0
APR DRG Description,2125754,335,"NEONATE BIRTH WEIGHT > 2499 GRAMS, NORMAL NEWB...",165929,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2125754.0,NaN,NaN,NaN,10.282674,5.964792,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2125754,26,DISEASES & DISORDERS OF THE CIRCULATORY SYSTEM,269418,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2125754.0,NaN,NaN,NaN,2.137231,0.951716,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2125280,4,Moderate,785246,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2125280,4,Minor,1073037,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2125754,3,Medical,1624519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2125754,9,Medicare,867570,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,1011708,9,Medicaid,421148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,282618,9,Self-Pay,162952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,204003,81,03200,16934,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Emergency Department Indicator,2125754,2,Y,1335889,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2125754,1864848,"3,794.00",317,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Costs,2125754,1616535,"4,157.08",318,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
Describe - 2024
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Health Service Area,2191442,8,New York City,996124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital County,2191442,57,New York,389375,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Operating Certificate Number,2191442.0,NaN,NaN,NaN,5087131.520291,2245914.005845,101000.0,2953000.0,5957001.0,7002032.0,7004010.0
Permanent Facility Id,2191442.0,NaN,NaN,NaN,1279.495557,1869.344069,1.0,541.0,1117.0,1456.0,15620.0
Facility Name,2196737,203,MOUNT SINAI HOSPITAL,53353,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age Group,2196737,5,70 or Older,706970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip Code,2154765,50,112,266231,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,2196737,3,F,1195617,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Race,2196737,4,White,1147354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ethnicity,2196737,4,Not Span/Hispanic,1540538,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length of Stay,2196737,120,2,464690,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type of Admission,2196737,6,Emergency,1460204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Patient Disposition,2196737,19,Home or Self Care,1441830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discharge Year,2196737.0,NaN,NaN,NaN,2024.0,0.0,2024.0,2024.0,2024.0,2024.0,2024.0
CCSR Diagnosis Code,2196737,478,PNL001,199274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Diagnosis Description,2196737,478,LIVEBORN,199274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Code,1552973,320,PGN002,115706,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CCSR Procedure Description,1552973,320,SPONTANEOUS VAGINAL DELIVERY,115706,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR DRG Code,2196737.0,NaN,NaN,NaN,414.332446,244.096264,1.0,194.0,383.0,640.0,956.0
APR DRG Description,2196737,336,"NEONATE BIRTH WEIGHT > 2499 GRAMS, NORMAL NEWB...",168494,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR MDC Code,2196737.0,NaN,NaN,NaN,10.302935,5.985493,0.0,5.0,9.0,15.0,25.0
APR MDC Description,2196737,26,DISEASES AND DISORDERS OF THE CIRCULATORY SYSTEM,277625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Severity of Illness Code,2196737.0,NaN,NaN,NaN,2.145497,0.925232,0.0,1.0,2.0,3.0,4.0
APR Severity of Illness Description,2196737,5,Moderate,820465,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Risk of Mortality,2196737,5,Minor,1108093,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APR Medical Surgical Description,2196737,3,Medical,1686244,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 1,2196510,9,Medicare,929267,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 2,992329,9,Medicaid,420954,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment Typology 3,240038,9,Self-Pay,124253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Birth Weight,207822,67,3200,17427,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Emergency Department Indicator,2196737,2,Y,1377141,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Charges,2196737.0,NaN,NaN,NaN,90625.430221,189402.170295,0.0,23576.38,47243.79,94515.16,19694856.95
Total Costs,2196737.0,NaN,NaN,NaN,26416.584062,55372.286312,0.0,7415.88,14110.45,27788.34,6701232.23